type Score {
  home: Int
  away: Int
}

type Periods {
  first: Score
  second: Score
  overtime: Score
  secondOvertime: Score
}

type Country {
  id: ID!
  name: String!
  code: String
  flag: String
}

type Arena {
  name: String
  capacity: Int
  location: String
}

type League {
  id: ID!
  name: String!
  logo: String!
  country: Country
  type: String
  teams: [Team]
}

type Game {
  id: ID!
  date: String
  time: String
  timestamp: Int
  timezone: String
  week: String
  status: String
  country: Country
  league: League
  teams: [Team]
  score: Score
  periods: Periods
}

type Team {
  id: ID!
  name: String!
  logo: String!
  country: Country
  national: Boolean
  founded: Int
  arena: Arena
  upcomingGames: [Game]
  pastGames: [Game]
}

type Query {
  getTeams (year: String!, leagueID: String!): [Team]!
  getLeagues (countryID: String, year: String, leagueID: String): [League]!
}